version: '3'
networks:
  isolated:
    driver_opts:
      com.docker.network.bridge.enable_icc: "false"
      com.docker.network.bridge.enable_ip_masquerade: "false"
services:
  postgres_server:
    build: ./postgres_server
    ports:
      - "5432:5432"
    networks:
      - isolated
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_INITDB_ARGS="--auth-host=md5"
  adminer:
    image: adminer
    networks:
      - isolated
    ports:
      - "8080:8080"
  ldap-service:
    build: ./openldap
    hostname: ldap-service
  phpldapadmin-service:
    build: ./phpldapadmin
    hostname: phpldapadmin-service
    links:
      - ldap-service:ldap-host
    ports:
      - "80:80"
  syncer-service:
    build: ./syncer

#docker run --name ldap-service --hostname ldap-service --detach osixia/openldap:1.1.8
#docker run -p 80:80 --name phpldapadmin-service --hostname phpldapadmin-service --link ldap-service:ldap-host --env PHPLDAPADMIN_HTTPS=false --env PHPLDAPADMIN_LDAP_HOSTS=ldap-host --detach osixia/phpldapadmin:0.6.12
