version: '3'
services:
  postgres-server:
    build: ./postgres_server
    hostname: postgres_server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - POSTGRES_INITDB_ARGS="--auth-host=md5"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  ldap-server:
    build: ./openldap
    hostname: ldap_server
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_CONFIG_PASSWORD=${LDAP_ADMIN_PASSWORD}
    volumes:
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
  phpldapadmin:
    build: ./phpldapadmin
    hostname: phpldapadmin
    ports:
      - "8888:80"
  syncer:
    build: ./syncer
    environment:
      - PGPASSWORD=${LDAP_ADMIN_PASSWORD}
      - PGUSER=admin
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_ADMIN_USER=admin
  jupyterhub:
    build: ./jupyterhub
    hostname: jupyterhub
    ports:
      - "8000:8000"

#docker run --name ldap-service --hostname ldap-service --detach osixia/openldap:1.1.8
#docker run -p 80:80 --name phpldapadmin-service --hostname phpldapadmin-service --link ldap-service:ldap-host --env PHPLDAPADMIN_HTTPS=false --env PHPLDAPADMIN_LDAP_HOSTS=ldap-host --detach osixia/phpldapadmin:0.6.12
