#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE read_only NOLOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';
    CREATE ROLE write_to_sandbox NOLOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION VALID UNTIL 'infinity';
    CREATE ROLE developer NOLOGIN NOSUPERUSER INHERIT NOCREATEDB CREATEROLE NOREPLICATION VALID UNTIL 'infinity';
    CREATE USER admin PASSWORD '$LDAP_ADMIN_PASSWORD' IN ROLE developer;
EOSQL
